FROM maven:3.9.11-eclipse-temurin-17-alpine as build
RUN apk add git
RUN git clone https://github.com/pavan01234567/spring-petclinic.git &&\
    cd spring-petclinic &&\
    mvn package

FROM  openjdk:25-ea-17-jdk as run 
RUN adduser -D -h /user/share/demo -s /bin/bash pavan 
USER pavan
WORKDIR /user/share/demo
COPY --from=build /target/*.jar
EXPOSE 8080/tcp
CMD ["java","-jar","*.jar"]